spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_ENDPOINT}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true
  sql.init.mode: always

  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    include: oauth

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: ${LOCATION}
      max-file-size: 5MB
      max-request-size: 5MB

api:
  aladin:
    key: ${ALADIN_KEY}

auth:
  jwt:
    secretKey: ${JWT_SECRET}
    accessExp: 3600000
    refreshExp: 604800000

cloud:
  aws:
    s3:
      bucket: bookitlist-profile
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
