spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_ENDPOINT}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: true
  sql.init.mode: always

  data:
    redis:
      host: localhost
      port: 6379

api:
  aladin:
    key: ${ALADIN_KEY}
